package app.packed.component;

// Hvad er scopet her...

// Heh, det er jo lidt som extension bean. Mht til scope...
///// Noget er Container, noget er Application...
public abstract non-sealed class BeanWirelet extends Wirelet {

}
