package app.packed.service.dep2;

// Keys....

// Set<Key<?>> requirement();
// Set<Key<?>> requirementOptional();

// Det faar du via denne parameter...

// Problemet er lidt hvis vi overskriver AnnotatedProviders...
// Tror bare ikke vi supportere det...
// Eller hvis vi skal kunne specificere annotationer skal vi jo egentlig goere det...
class RequirementSet {

}
